language: generic
sudo: required
env: SWIFT_VERSION=4.0-DEVELOPMENT-SNAPSHOT-2017-06-23-a

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)" && swift -version

script:
  - swift test
