language: generic
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env: SWIFT_VERSION=4.1
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      
    - os: osx
      osx_image: xcode9

script:
  - swift test
